stage

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -102,19 +102,35 @@ jobs:
     #needs: Build
     runs-on: self-hosted
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Set up Java
-        uses: actions/setup-java@v1
-        with:
-          java-version: '17'
-      - name: Build JAR
-        run: mvn clean package
-      - name: Upload JAR artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: my-app
-          path: ./target/*.jar
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Install Docker
+      uses: docker/setup-docker@v1
+
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+
+    - name: Pull Docker image
+      run: docker pull ${IMAGE_NAME}:${IMAGE_TAG}
+
+    - name: Start Docker container
+      run: docker run -dti --name MoonPageApp -p 8080:8080 ${IMAGE_NAME}:${IMAGE_TAG}
+
+    - name: Wait for application to start
+      run: sleep 30
+
+    - name: Verify application is running
+      run: |
+        response=$(curl --write-out %{http_code} --silent --output /dev/null http://44.200.128.81:8080/)
+        if [ $response -ne 200 ]; then
+          echo "Application failed to start"
+          exit 1
+        fi
+
   
   Selenium-test:
     # needs: build
@@ -140,7 +156,7 @@ jobs:
          path: ./*
 #Deployment in Staging Environment
   Deploy_Staging_Environment:
-    needs: Selenium-test
+    #needs: Selenium-test
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
@@ -157,7 +173,7 @@ jobs:
         aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{env.ECS_SERVICE}} --task-definition ${{ env.ECS_TASK_DEFINITION }}
   #Jmeter Testing for load and performance 
   Performance_Testing:
-    needs: Deploy_Staging_Environment 
+    #needs: Deploy_Staging_Environment 
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
