update

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,11 +1,8 @@
 name: GITHUB-CICD
 on: [push]
 env:
-   ARTIFACTORY_URL: http://10.53.105.21:8082/
-   ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
-   ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
-   IMAGE_NAME: pavan9999/github-actions
-   IMAGE_TAG: MoonPageApp
+   DOCKER_IMAGE_NAME: pavan9999/github-actions
+   DOCKER_IMAGE_TAG: MoonPageApp
    AWS_REGION: us-east-1
    ECS_CLUSTER: ecs-cluster
    ECS_SERVICE: svc
@@ -29,7 +26,7 @@ jobs:
         with:
           name: MoonPageApp
           path: ./target/*.war
-  SonarQube:
+  SonarQube_Scanner:
     needs: Build
     runs-on: ubuntu-latest
     steps:
@@ -48,7 +45,7 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   OWASPDependencyCheck:
-    needs: SonarQube
+    needs: SonarQube_Scanner
     runs-on: ubuntu-latest
     steps:
       # OWASP Dependency Check(SCA)
@@ -80,7 +77,7 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
          name: junit-reports
-         path: ./target/surefire-reports/*
+         path: ./target/*
   CodeCoverage:
     needs: Junit_Test
     runs-on: ubuntu-latest
@@ -100,7 +97,7 @@ jobs:
         with:
          name: codecoverage-jacoco-report
          path: ./target/site/jacoco/index.html 
-  Docker-Image:
+  Build_Scan_Docker_Image:
     needs: CodeCoverage
     runs-on: ubuntu-latest
     steps:
@@ -115,64 +112,85 @@ jobs:
       - name: Build before create image
         run: mvn clean package
       # Build Docker image and Push into Docker Hub 
-      - name: Docker-Image-Build & Push
+      - name: Docker-Image-Build 
+        run: |
+            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+            docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
+        # Docker Image Scan Trivy Tool installing
+      - name: Install Trivy 
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y curl
+          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
+      # Docker Image Scanning
+      - name: Scan Docker Image
+        run: |
+           trivy image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} > image-scan-report.html
+           trivy --no-progress --exit-code 0 --severity HIGH,CRITICAL --auto-refresh ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
+      - name: Upload scan results
+        uses: actions/upload-artifact@v2
+        with:
+           name: trivy-scan-results
+           path: ./*.html     
+  Docker_Image_Push: 
+     needs: Build_Scan_Docker_Image
+     runs-on: ubuntu:latest
+     steps:
+      - uses: actions/checkout@v2
+      - name: Set up JDK 11
+        uses: actions/setup-java@v1
+        with:
+          java-version: "11"
+          distribution: adopt
+          cache: maven
+      - name: Build before create image
+        run: mvn clean package
+      # Build Docker image and Push into Docker Hub 
+      - name: Docker Image Push Into Docker Hub
         uses: mr-smithers-excellent/docker-build-push@v5
         with:
-          image: ${IMAGE_NAME}
-          tags: ${IMAGE_TAG}
+          image: ${DOCKER_IMAGE_NAME}
+          tags: ${DOCKER_IMAGE_TAG}
           registry: docker.io
           dockerfile: Dockerfile
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-
   Deploy_QA_Environment:
-    #needs: Build
+    needs: Docker_Image_Push
     runs-on: self-hosted
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up JDK 11
-      uses: actions/setup-java@v1
-      with:
+     - uses: actions/checkout@v2
+     - name: Set up JDK 11
+     - uses: actions/setup-java@v1
+       with:
           java-version: "11"
           distribution: adopt
           cache: maven
-    #- name: Checkout code
-     # uses: actions/checkout@v2
-    #- name: Install Java and Maven
-    # run: |
-         #sudo apt install openjdk-11-jdk
-         #sudo apt install maven 
-    - name: Maven Build 
-      run: sudo mvn clean package   
-    - name: Install Docker
-      run: |
-           sudo apt-get update
-           sudo apt-get -y install docker.io    
-    - name: Pull Docker image
-      run: |
+     - name: Maven Build 
+       run: mvn clean package     
+     - name: Pull Docker image
+       run: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-           sudo docker pull ${IMAGE_NAME}:${IMAGE_TAG}
+           sudo docker pull ${Docker_IMAGE_NAME}:${Docker_IMAGE_TAG}
 
-    - name: Start Docker container
-      run: |
-           sudo docker run -d --name MoonPageApp -p 8080:8080 ${IMAGE_NAME}:${IMAGE_TAG}
+     - name: Start Docker container
+       run: |
+            sudo docker run -d --name MoonPageApp -p 8080:8080 ${Docker_IMAGE_NAME}:${Docker_IMAGE_TAG}
 
-    - name: Wait for application to start
-      run: sleep 30
+     - name: Wait for application to start
+       run: sleep 30
 
-    - name: Verify application is running
-      run: |
-        response=$(curl --write-out %{http_code} --silent --output /dev/null http://44.200.128.81:8080/)
-        if [ $response -ne 200 ]; then
-          echo "Application failed to start"
-          exit 1
-        fi
-
-  
+     - name: Verify application is running
+       run: |
+         response=$(curl --write-out %{http_code} --silent --output /dev/null http://44.204.226.84:8080/)
+         if [ $response -ne 200 ]; then
+           echo "Application failed to start"
+           exit 1
+         fi
   Selenium-test:
-    # needs: build
-     runs-on: ubuntu-latest
-     steps:
+    needs: Deploy_QA_Environment
+    runs-on: ubuntu-latest
+    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 11
         uses: actions/setup-java@v3
@@ -190,10 +208,10 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
          name: selenium-results
-         path: ./*
-#Deployment in Staging Environment
+         path: ./*            
+  #Deployment in Staging Environment
   Deploy_Staging_Environment:
-    #needs: Selenium-test
+    needs: Selenium-test
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
@@ -208,7 +226,8 @@ jobs:
     - name: Deploy to Amazon ECS
       run: |
         aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{env.ECS_SERVICE}} --task-definition ${{ env.ECS_TASK_DEFINITION }}
-  #Jmeter Testing for load and performance 
+      
+   #Jmeter Testing for load and performance 
   Performance_Testing:
     #needs: Deploy_Staging_Environment 
     runs-on: ubuntu-latest
@@ -219,17 +238,14 @@ jobs:
        uses: actions/setup-java@v1
        with:
           java-version: 11
-           distribution: adopt
+          distribution: adopt
           cache: maven
+     - name: Performance Testing
+       run: mvn verify --from jmeter-pom.xml
      - name: Upload test results    
        uses: actions/upload-artifact@v2
        with:
           name: jmeter-test-results
-          path: ./*
-               
+          path: ./*     
         
         
-        
-        
-        
-  
